# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: tango
report_sizes: true
dist: ./release

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=jsonv2
  - NODE_ENV=production
  - VITEST=true

before:
  hooks:
    - go mod download
    - go mod tidy
    - pnpm install --ignore-scripts --frozen-lockfile
    - pnpm run build
    # - swag init --output ./api -d cmd,internal,modules,pkg -g tango/main.go --quiet
    # - swag fmt --dir ./api

builds:
  - id: build_noncgo
    main: ./cmd
    binary: '{{.Os}}_{{.Arch}}/{{.ProjectName}}'
    no_main_check: true
    no_unique_dist_dir: true
    goos: ['darwin', 'linux', 'windows']
    goarch: ['amd64', 'arm64']
    buildmode: pie
    tags: ['release']
    flags: ['-trimpath', '-buildvcs=false']
    ldflags:
      - -w -s -extldflags '-static'
      - -X 'tango/internal/config.AppVersion={{.Tag}}'
      - -X 'tango/internal/config.BuildHash={{.ShortCommit}}'
      - -X 'tango/internal/config.BuildDate={{.Date}}'

archives:
  - formats: [tar.gz]
    ids: [build_noncgo]
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: 'v{{ incpatch .Version }}'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
  mode: prepend
  draft: true

# kos:
#   - repositories:
#       - ghcr.io/riipandi/tango
#     tags:
#       - "v{{.Version}}"
#     bare: true
#     platforms:
#       - linux/amd64
#       - linux/arm64

# dockers_v2:
#   - id: distroless
#     dockerfile: ./deploy/Dockerfile
#     images: ['ghcr.io/riipandi/tango']
#     tags:
#       - "v{{ .Version }}"
#       - "{{ if .IsNightly }}nightly{{ end }}"
#       - "{{ if not .IsNightly }}latest{{ end }}"
#     labels:
#       "org.opencontainers.image.name": "{{.ProjectName}}"
#       "org.opencontainers.image.version": "{{.Version}}"
#       "org.opencontainers.image.created": "{{.Date}}"
#       "org.opencontainers.image.revision": "{{.FullCommit}}"
#       "org.opencontainers.image.source": "{{.GitURL}}"
#       "org.opencontainers.image.licenses": "Proprietary"
#     platforms: ['linux/amd64', 'linux/arm64']
#     build_args:
#       DOCKER_IMAGE: 'ghcr.io/riipandi/tango'
#       BUILD_VERSION: '{{.Version}}'
#       BUILD_HASH: '{{.Commit}}'
#       GO_VERSION: 1.26.1
#       PLATFORM: linux/amd64
#       DISTROLESS_TAG: nonroot

# binary_signs:
#   -
#     # Name of the signature file.
#     #
#     # Default: '${artifact}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'.
#     # Templates: allowed.
#     signature: "${artifact}_sig"
#     cmd: gpg

#     # Command line arguments for the command
#     #
#     # to sign with a specific key use
#     # args: ["-u", "<key id, fingerprint, email, ...>", "--output", "${signature}", "--detach-sign", "${artifact}"]
#     #
#     # Default: ["--output", "${signature}", "--detach-sign", "${artifact}"].
#     # Templates: allowed.
#     args: ["--output", "${signature}", "${artifact}", "{{ .ProjectName }}"]
#     artifacts: binary
#     stdin: "{{ .Env.GPG_PASSWORD }}"
#     stdin_file: ./.env.password

#     # Sets a certificate that your signing command should write to.
#     #
#     # You can later use `${certificate}` or `.Env.certificate` in the `args` section.
#     #
#     # This is particularly useful for keyless signing with cosign, and should
#     # not usually be used otherwise.
#     #
#     # Note that this should be a name, not a path.
#     #
#     # Templates: allowed.
#     certificate: '{{ trimsuffix .Env.artifact ".tar.gz" }}.pem'
#     env:
#       - FOO=bar
#       - HONK=honkhonk
#     output: true
