# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: gogon

x-common: &common
  networks: ['intranet']
  extra_hosts: ['host.docker.internal:host-gateway']
  restart: unless-stopped

services:
  # gogon:
  #   <<: *common
  #   build:
  #     context: .
  #     dockerfile: ./deploy/Dockerfile
  #     args:
  #       DISTROLESS_TAG: ${DISTROLESS_TAG:-nonroot}
  #       NODE_VERSION: ${NODE_VERSION:-24.14}
  #       GO_VERSION: ${GO_VERSION:-1.26.1}
  #   # platform: linux/amd64
  #   hostname: gogon
  #   volumes: ["./storage:/srv/storage:rw"]
  #   ports: ["3000:3000"]
  #   env_file: "./.env.local"
  #   healthcheck:
  #     test: ["CMD", "/srv/gogon", "health"]
  #     interval: 3s
  #     timeout: 5s
  #     retries: 3
  #   depends_on:
  #     pgsql: { condition: service_healthy }
  #     minio: { condition: service_healthy }

  pgsql:
    <<: *common
    # image: dhi.io/postgres:${PGSQL_VERSION:-18} # production
    # image: dhi.io/postgres:${PGSQL_VERSION:-18-debian13-dev}
    image: postgres:${PGSQL_VERSION:-18-alpine}
    hostname: postgres
    ports: ['5432:5432']
    volumes:
      - 'pgsql_data:/var/lib/postgresql/18/docker:rw'
      - ./scripts/extradb.sh:/docker-entrypoint-initdb.d/extradb.sh
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securedb
      PG_DATABASES: testdb,analytics
    shm_size: 128m # set shared memory limit
    mem_limit: 256m # set memory limit
    cpus: 1.0 # set CPUs limit
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 3s
      timeout: 5s
      retries: 3

  mailpit:
    <<: *common
    image: axllent/mailpit:${MAILPIT_VERSION:-latest}
    hostname: mailpit
    volumes: ['mailpit_data:/data:rw']
    ports: ['1025:1025', '8025:8025']
    environment:
      TZ: Asia/Jakarta
      MP_TAGS_USERNAME: true
      MP_DISABLE_VERSION_CHECK: true
      MP_ALLOW_UNTRUSTED_TLS: true
      MP_UI_BIND_ADDR: 0.0.0.0:8025
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_AUTH: 'maileruser1:mailerpass1 maileruser2:mailerpass2'
    healthcheck:
      test: ['CMD-SHELL', 'nc -vz 127.0.0.1 8025 || exit 1']
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  redis:
    <<: *common
    image: redis:${REDIS_VERSION:-8-alpine}
    hostname: redis
    ports: ['6379:6379']
    volumes: ['redis_data:/data:rw']
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      ALLOW_EMPTY_PASSWORD: 'no' # recommended only for development
    command: '--appendonly yes --appendfsync everysec --requirepass securedb'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --no-auth-warning -a securedb ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    ulimits:
      memlock: -1
      nofile:
        soft: 262144
        hard: 262144
    shm_size: 128m # set shared memory limit
    mem_limit: 256m # set memory limit
    cpus: 1.0 # set CPUs limit

  minio:
    <<: *common
    image: minio/minio:${MINIO_VERSION:-latest}
    hostname: minio
    ports: ['9100:9100', '9101:9101']
    environment:
      # docker-compose exec minio /usr/bin/mc alias ls
      MINIO_BROWSER_LOGIN_ANIMATION: off
      MINIO_DOMAIN: ${MINIO_DOMAIN:-localhost}
      MINIO_ROOT_USER: ${STORAGE_S3_ACCESS_KEY_ID:-s3admin}
      MINIO_ROOT_PASSWORD: ${STORAGE_S3_SECRET_ACCESS_KEY:-s3passw0rd}
      MC_HOST_local: http://${MINIO_ROOT_USER:-s3admin}:${MINIO_ROOT_PASSWORD:-s3passw0rd}@localhost:9100
    volumes: ['./storage/minio_data:/data:rw']
    command: server /data --address "0.0.0.0:9100" --console-address "0.0.0.0:9101"
    shm_size: 256m # set shared memory limit
    mem_limit: 256m # set memory limit
    cpus: 1.0 # set CPUs limit
    post_start:
      - command: sh -c "/usr/bin/mc mb local/devbucket --ignore-existing"
      - command: sh -c "/usr/bin/mc mb local/testbucket --ignore-existing"
      - command: sh -c "/usr/bin/mc mb local/dbarchive --ignore-existing"
      - command: sh -c "/usr/bin/mc anonymous set download local/devbucket"
      - command: sh -c "/usr/bin/mc anonymous set download local/testbucket"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9100/minio/health/live']
      interval: 3s
      timeout: 5s
      retries: 3

  nginx:
    <<: *common
    image: nginx:${NGINX_VERSION:-mainline-alpine-slim}
    hostname: nginx
    ports: ['9180:9180']
    configs:
      - source: nginx_config
        target: /etc/nginx/templates/default.conf.template
    healthcheck:
      test: ['CMD', 'nc', '-vz', '127.0.0.1', '9180']
      interval: 3s
      timeout: 5s
      retries: 3
    depends_on:
      minio: { condition: service_started }

configs:
  nginx_config:
    content: |
      server {
          listen 9180;
          server_name localhost;
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header Access-Control-Allow-Origin * always;
          add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, HEAD, OPTIONS" always;
          add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization" always;
          add_header Access-Control-Expose-Headers "Content-Length,Content-Range,ETag" always;
          location / {
              proxy_pass http://minio:9100/devbucket/;
              proxy_http_version 1.1;
              proxy_set_header Connection "";
              proxy_buffering off;
              proxy_redirect off;
              proxy_connect_timeout 300;
              proxy_send_timeout 300;
              proxy_read_timeout 300;
              send_timeout 300;
          }
      }

volumes:
  pgsql_data:
    driver: local
  mailpit_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  intranet:
    name: intranet
    driver: bridge
