# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GIT_SHA:
    sh: git rev-parse --short HEAD
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  DEFAULT_BUILD_VERSION:
    sh: cat package.json | jq -r .version
  BUILD_VERSION: "{{.BUILD_VERSION | default .DEFAULT_BUILD_VERSION}}"
  PKG_FLAGS_PREFIX: github.com/riipandi/gogon/pkg
  IMAGE_NAME: riipandi/gogon
  CONTAINER_NAME: gogon

includes:
  dev: tasks/development.yml
  build: tasks/release.yml
  docker: tasks/docker.yml

tasks:
  default:
    silent: true
    desc: Print all available tasks
    cmd: "task --list-all"

  # -----------------------------------------------------------------------------------------------
  # Tasks for Docker development
  # -----------------------------------------------------------------------------------------------

  start:
    silent: true
    desc: Run the compiled application
    deps: ["build"]
    cmd: ./build/gogon --address 127.0.0.1:3080

  generate-key:
    silent: true
    desc: Generate a random secret key
    cmd: openssl rand -base64 500 | tr -dc 'a-zA-Z0-9' | fold -w 40 | head -n 1

  update-deps:
    silent: true
    desc: Update NPM dependencies
    cmd: pnpm exec npm-check-updates --configFileName .ncurc.json

  code:check:
    silent: true
    desc: Check code quality
    cmds:
      - pnpm exec biome check --apply .
      - gosec -quiet -no-fail ./...

  code:format:
    silent: true
    desc: Format code
    cmds:
      - pnpm exec biome format . --write

  code:lint:
    silent: true
    desc: Lint code
    cmds:
     - pnpm exec biome lint --apply .
     - golangci-lint run -c golangci.yml ./...
