# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    silent: true
    desc: Start development mode
    deps: ["prepare"]
    cmd: air -c air.toml

  install:
    silent: true
    desc: Install required dependencies
    cmds:
      - mkdir -p {{.ROOT_DIR}}/build
      - go mod download
      - go mod tidy
      - go mod vendor
      - pnpm install

  prepare:
    silent: true
    desc: Start the database and local mail server
    cmd: docker-compose -f docker-compose.yml up -d

  cleanup:
    silent: true
    desc: Stop dev server and cleanup generated files
    cmds:
     - docker-compose -f docker-compose.yml down --remove-orphans
     - find . -name *_gen.go -type f -delete
     - find . -name *_templ.go -type f -delete
