# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  DOCKER_BUILDKIT: 1

tasks:
  build:
    silent: true
    desc: Build Docker image
    cmds:
      - |
        docker build . \
          --build-arg BUILD_VERSION={{.BUILD_VERSION}} \
          -t {{.IMAGE_NAME}}:{{.BUILD_VERSION}} \
          -t {{.IMAGE_NAME}}:latest
      - docker image list | grep {{.IMAGE_NAME}}

  push:
    silent: true
    desc: Push Docker image to container registry
    cmds:
      - docker push {{.IMAGE_NAME}}:latest
      - docker push {{.IMAGE_NAME}}:{{.BUILD_VERSION}}

  run:
    silent: true
    desc: Run Docker container
    cmd: docker run --rm -it --name {{.CONTAINER_NAME}} --env-file .env.docker -p 3080:3080 {{.IMAGE_NAME}}:latest

  shell:
    silent: true
    desc: Run Docker container shell
    cmd: docker run --rm -it --env-file .env.docker --entrypoint sh {{.IMAGE_NAME}}:latest

  migrate:
    silent: true
    desc: Run database migrations inside Docker container
    # cmd: docker run --rm -it --env-file .env.docker --entrypoint /usr/bin/gogon {{.CONTAINER_NAME}} migrate
    cmd: docker run --rm -it --env-file .env.docker --entrypoint /usr/bin/gogon {{.IMAGE_NAME}}:latest migrate

  validate:
    silent: true
    desc: Check compiled application version
    cmd: docker run --rm -it --env-file .env.docker --entrypoint /usr/bin/gogon {{.IMAGE_NAME}}:latest version
