# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    silent: true
    desc: Build the application binary
    vars:
      FLAG_BUILD_VERSION: "{{.PKG_FLAGS_PREFIX}}.Version={{.BUILD_VERSION}}"
      FLAG_BUILD_DATE: "{{.PKG_FLAGS_PREFIX}}.BuildDate={{.BUILD_DATE}}"
    env:
      CGO_ENABLED: 0
      LD_FLAGS: "-w -s -extldflags '-static' -X {{.FLAG_BUILD_VERSION}} -X {{.FLAG_BUILD_DATE}}"
      NODE_ENV: production
    cmds:
      - node esbuild.config.js && templ generate
      - go build --ldflags="$LD_FLAGS" -a -o build/gogon cmd/app/main.go
      - ls -lh {{.ROOT_DIR}}/build && {{.ROOT_DIR}}/build/gogon version

  single:
    silent: true
    desc: GoReleaser build single target
    cmd: goreleaser build --single-target --snapshot --clean

  snapshot:
    silent: true
    desc: GoReleaser relese snapshot
    cmd: goreleaser release --snapshot --clean --skip-publish

  release:
    silent: true
    desc: GoReleaser build and release
    cmd: goreleaser release --clean
