# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

# @reference: https://stackoverflow.com/questions/59813998/github-actions-splitting-workflow-file
# @reference: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup-sdk
description: Prepare development environment

inputs:
  nodeVersion:
    description: 'Nodejs version'
    required: false
    default: '20'
  pnpmVersion:
    description: 'PNPM version'
    required: false
    default: '8'
  goVersion:
    description: 'Golang version'
    required: false
    default: '>=1.22'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpmVersion }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Setup Golang toolchain
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.goVersion }}
