package config

// IMPORTANT NOTICE: DO NOT EDIT THIS FILE MANUALLY
// Values in this file are automatically generated during the build process.
// Variable values are injected at build time via ldflags.
// Any manual changes will be overwritten.

import (
	"fmt"
	"runtime"
)

var (
	AppName    = "gogon"
	AppVersion = "0.0.0"
	BuildHash  = "unknown"
	BuildDate  = "0000-00-00T00:00:00Z"
	Platform   = fmt.Sprintf("%s/%s", runtime.GOOS, runtime.GOARCH)
)
