# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# git tag --delete v0.0.1
# git tag v0.0.1 -m "version bump"
# git push origin --tags

name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Build frontend
        run: pnpm install

      # The prebuilt golangci-lint doesn't support go 1.18+ yet
      # @ref: https://github.com/golangci/golangci-lint/issues/2649
      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3

      - name: Run unit tests
        run: go test -v ./...

      # Code signing:
      # @ref: https://github.com/goreleaser/goreleaser-action?tab=readme-ov-file#signing
      # - name: Import GPG key
      #   id: import_gpg
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
