# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test

on:
  push:
    branches: ['**']
    tags-ignore: ['*']
  pull_request:

permissions: read-all

env:
  CGO_ENABLED: 0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # ubuntu-latest, macOS-latest, windows-2019
        os: [ubuntu-latest]
        go-version: ['1.26.1']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk
        with:
          goVersion: ${{ matrix.go-version }}

      - name: Install required toolchain
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - uses: bufbuild/buf-action@v1
        with:
          github_token: ${{ github.token }}
          setup_only: true

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          pnpm install --ignore-scripts --frozen-lockfile
          go mod download && go mod tidy
          buf lint && buf generate --config buf.yaml

      # - name: Install and generate templates
      #   run: |
      #     go install github.com/a-h/templ/cmd/templ@latest
      #     templ generate

      - name: Check code quality (frontend)
        run: |
          pnpm exec oxfmt --check
          pnpm exec oxfmt --write .
          pnpm exec oxlint --fix .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          github-token: ${{ github.token }}
          install-mode: binary
          version: v2.11

      - name: Check code quality (backend)
        run: |
          go vet ./...
          golangci-lint run -c golangci.yml ./...

      - name: Run unit tests (backend)
        run: go test -v ./...

      - name: Build the application
        run: pnpm run build
